FROM alpine:3.21.0

RUN apk update && apk add --no-cache \
  gcc libc-dev g++ graphviz python3 py-pip python3-dev ttf-opensans curl fontconfig npm

COPY web /app
WORKDIR /app
COPY /scripts/entrypoint.sh /scripts/start.sh /scripts/
RUN chmod +x /scripts/*.sh

RUN pip3 install -r requirements.txt

# add diagrams-xtd
RUN pip3 install diagrams-0.22.0.5.tar.gz

# add fonts to support CJK languages
RUN curl -O https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip \
&& mkdir -p /usr/share/fonts/NotoSansCJKjp \
&& unzip NotoSansCJKjp-hinted.zip -d /usr/share/fonts/NotoSansCJKjp/ \
&& rm NotoSansCJKjp-hinted.zip \
&& fc-cache -fv

ENTRYPOINT ["/scripts/entrypoint.sh"]
